# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber'

require 'capybara'
require 'capybara/cucumber'
require 'capybara/session'
require 'capybara/poltergeist'

require "spar"
Capybara.app = Spar.app
Spar.settings["environment"] = "test"

Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new app, :inspector => true
end
Capybara.default_driver = :poltergeist

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css
